### ISSUE TITLE
Get scripts into a version control system

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/MTR#34]
@schwehr showed me how to use the builtin git support in EE, so we can start there, and hopefully set up a hook to sync this repo to the EE remote.

![unnamed](https://cloud.githubusercontent.com/assets/2676083/16206842/4e3c5248-36f8-11e6-9f2e-b6f074ac2703.png)

Hover over the little I to get the remote URL:

![unnamed-1](https://cloud.githubusercontent.com/assets/2676083/16206847/51ee16b0-36f8-11e6-8eec-73a572fb48a2.png)

**Comment by apericak** [comment]
We have decided to keep everything on GitHub rather than using GEE's internal Git, but this means that anybody editing the script must copy the current script from GitHub into the GEE Playground, and then copy back changes to a branch here. (And of course make changes here via a branch and pull request.)
