### ISSUE TITLE
Landsat 3 Classification

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#43]
Using Andrew's Landsat 1-3 script, we are now able to export greenest pixel composites and derived NDVI's from landsat 1, 2, and 3 imagery in Earth Engine. In downloading one year annual composites, I noticed significant error, patches of missing data or holes, in the landsat 1 and 2 composites. My solution was to just make multi-year composites (landsat 1 was a 4 year composite and landsat 2 was a 3 year composite). This seemed to correct for the missing data, and I was relatively able to finish the point classifications. However, for landsat 3 I noticed not holes or missing data, but obvious strips of data that did not resemble the pixel values around them. Screenshot 1 and 3 below are examples of this. Screenshot 1 is a 7 year composite (scenes I and II) of landsat 3 (years 1978 to 1984). Screenshot 3 is just a 3 year composite of scene I. The NDVI's show the same odd strips of mismatched data, as screenshot 2 demonstrates (NDVI from the 7 year scene I and II composites). With the error in these composites and NDVI's, I cannot properly classify mining areas for landsat 3. 

![screen shot 2016-06-24 at 4 10 06 pm](https://cloud.githubusercontent.com/assets/17166201/16349334/4f3d07b0-3a26-11e6-8404-4d4c8ab4bc47.png)

![screen shot 2016-06-24 at 4 10 23 pm](https://cloud.githubusercontent.com/assets/17166201/16349335/4f3e6e16-3a26-11e6-936b-2e12f5e01916.png)

![screen shot 2016-06-24 at 4 10 51 pm](https://cloud.githubusercontent.com/assets/17166201/16349336/4f43fc78-3a26-11e6-970a-5338af4b22dc.png)

**Comment by apericak** [comment]
That those errors are showing up across all 7 years means either a) there just aren't many images in that area (maybe); or b) it's a systematic error that I should be able to correct for. I'll look into it and tell you what I can figure out.

**Comment by apericak** [comment]
@TwigBeard So I've been looking at this and the Landsat 3 images are indeed pretty error-prone and have a lot of clouds that the cloud filtering algorithm isn't catching. I think the best approach is to ignore  LS3 imagery, as you were suggesting, and we'll just have a small gap from 1982 (when Landsat 2 ends) until 1984 (when Landsat 5 begins), since Landsat 4 doesn't completely cover our study area within that gap. If you think that's an acceptable answer, go ahead and close this issue, but we will be sure to mention this at the check-up meeting tomorrow.
