### ISSUE TITLE
Optimize Erode/Dilate Distance & Removing Small Areas

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#44]
_Blocks: #49_
@apericak We need to determine the best distance to use for erosion/dilation in order to remove small areas being classified as active mine.  Are there other options such as filtering by area that can assist in this process?
 - We are currently using a distance of 30 meters for erosion/dilation

@TwigBeard will help you with this

**Comment by cjthomas730** [comment]
@apericak @davidkroodsma this is something which I would like to discuss either during our next stand-up (07/07) and/or on this ticket. What are your thoughts?

Our erosion/dilation work is currently a 4 step process:

```java
// ERODE & DILATE
  var MTR_ER_DI_DI_ER = MTR_clipped
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')) 
//  ^^^ Erode in to remove small areas
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(30, 'meters'))  
// ^^^ Dilate out to restore large areas to previous extent
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(30, 'meters'))  
// ^^^ Dilate out to remove holes in active mine areas
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')); 
// ^^^ Erode in to restore boundary to previous extent 
```

Firstly, I think that this could be boiled down to three, by combining the two dilation's into on 1 step, 
ie: 
```java
  var MTR_ER_DI_DI_ER = MTR_clipped
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')) 
//  ^^^ Erode in to remove small areas
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(60, 'meters'))  
// ^^^ Dilate out to restore large areas to previous extent and remove holes in active mine areas
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')); 
// ^^^ Erode in to restore boundary to previous extent 
```

But secondly I think we may also want to buffer out by a larger distance to remove, which would help to cover the holes within mining areas, and allow roads which lie within the mine to be classified as well. Maybe something along these lines:
```java
  var MTR_ER_DI_DI_ER = MTR_clipped
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')) 
//  ^^^ Erode in to remove small areas
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(90, 'meters'))  
// ^^^ Dilate out to resore large areas to previous extent and remove holes in active mine areas
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(60, 'meters')); 
// ^^^ Erode in to restore boundary to previous extent
```

**Comment by davidkroodsma** [comment]
@cjthomas730 Good call that you could remove a step in this.

Also, we should do sensitivity analysis on these erode and dilate numbers. How do we choose the optimal size?

**Comment by cjthomas730** [comment]
I agree, @apericak do you have any ideas about this?

**Comment by apericak** [comment]
In terms of distance, my guess would be to use multiples of 60 so that it aligns with early Landsats with their 60 m resolution. Regarding the script itself, it sounds like combining the two dilation steps should be alright, but I would have to see some comparisons to make sure. E.g., maybe getting the maximum of cells within 60 m would actually be a different result from the maximum of 30 m twice. But maybe to be on the safe side, to prevent any unforeseen changes, we do keep it as two dilations (or three, to make it 90 m). Tl;dr, probably need to test both situations out and see if having one dilation step makes a drastic difference.

Moreover, what I *hope* will happen is that having a specific threshold per year will actually eliminate a fair amount of small error. We will still definitely need to do this erosion/dilation to clean up the boundaries, but ideally the more-precise threshold will eliminate some small, isolated errors.
