### ISSUE TITLE
Academic Paper Process

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#53]
@apericak could you please look into the academic paper writing process, and give us a summary of what will need to happen for that? Can you also talk with Emily and Matt about possible journals for this paper?

**Comment by apericak** [comment]
I've talked Matt/Emily and some other PhD students here about this. Here are some things to think about:

**What journal to target?**
The most well-known remote sensing journal is [_Remote Sensing of Environment_](http://www.journals.elsevier.com/remote-sensing-of-environment/), which does contain a fair amount of methods papers. If we go this route, though, we will also want to do some basic analysis (summary stats, maybe showing some change over time, etc.) to make it more than just methods. This and other related journals tend to be more focused on academic users, and of course are not open-access.

Alternatively, we could publish in an open-access journal, so that anybody using the dataset could also access the paper. While _[PLOS ONE](http://journals.plos.org/plosone/)_ is perhaps the most famous in this realm (and a viable option), I was also recommended to consider _[PeerJ](https://peerj.com/)_. Note that these aren't explicitly RS journals, but nevertheless they are usually well-regarded and have a large impact, since they are so readily available.

We should also be sure _not_ to target certain journals; for instance, I was advised against _International Journal for Remote Sensing_ since it has a reputation of poor editing.

Finally, we could also consider whether we have a specific "target audience" that we expect to use this data and methods. Obviously this will be a broad-ranging dataset, but if we cant think of some audience in particular we might want to focus on some specific journals read by people in that audience.

**Duke involvement**
Matt Ross (and Emily) will be willing to help write the paper; their contributions will mostly come from background information about coal mining in Appalachia, etc., and with editing the paper before submission.

Matt has also volunteered to help with some simple data visualizations via R / Shiny, since he now has a lot of experience with that. For instance, this might include some interactive web applications showing how mining came and went across the study extent.

If we publish with Duke researchers on board, that means we can get access to server space at Duke's library for hosting data, files, or other scripts. I'm not sure what sort of capability SkyTruth has in this regard, however, since it might be easier to just have you all host everything.

**Timeline**
I am only involved on this project through November at the latest, so my goal at least is to have a paper submitted by then. This will mean having our dataset approximately ready and validated by mid-August, with the paper submitted to the journal by the end of October (or possibly sooner if we do not opt for an open access journal.)

**Other Advice**
One PhD student told me this idea she has heard from her professor: "Write the abstract and make all the figures first, then write the rest of the paper." This makes sure that we are all agreed upon what to discuss in the paper, and makes the figures guide the paper. This should be relatively easy to accomplish since so much of our paper will be figure-based.

Most of our figures may be in supplemental material or might be online; i.e., we can only have a few static maps/charts for the actual paper. Nevertheless, those figures in the actual paper are very important since most people may not seek out a website or the supplemental material. So, we should be sure to spend some time working on those in-paper figures.

**Comment by cjthomas730** [comment]
Closing this issue, see the Academic Paper Process section of the [Andrew's Work Wiki page](https://github.com/SkyTruth/MTR/wiki/Andrew's-work).
