### ISSUE TITLE
Decide on Erode/Dilate Distance

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#69]
_See #44_

Based on our discussion on 07/12, for the time being we are going to use the 4 step Erosion-Dilation, although we will be looking in to whether we can compress it to 3 steps without altering the output.
We also decided to use buffer distances which are multiples of 60, so that the Erosion-Dilation will align with the resolution of Landsat 1-3. For the time being we will use a `60 meter` buffer.

@apericak we should update the master script to reflect this. The current (as of 07/13) Erosion-Dilation code:
``` java
  // Erode/dilate MTR sites to remove outliers (pixel clean-up)
  var MTR_eroded_dialated_dialated_eroded = MTR
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(30, 'meters'))
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters'))
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters'))
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(30, 'meters'));
  
  var MTR_masked = MTR_eroded_dialated_dialated_eroded.updateMask(MTR_eroded_dialated_dialated_eroded);
```
Dilates --> erodes --> erodes --> dilates using a 30 meter buffer distance. 

We should update this to reflect the use of the 60 meter buffer distance, as well as to change the order: erode --> dilate --> dilate --> erode:

```java
  // Erode/dilate MTR sites to remove outliers (pixel clean-up)
  var MTR_eroded_dialated_dialated_eroded = MTR
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(60, 'meters'))
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(60, 'meters'))
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(60, 'meters'))
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(60, 'meters'));
  
  var MTR_masked = MTR_eroded_dialated_dialated_eroded.updateMask(MTR_eroded_dialated_dialated_eroded);
```

**Comment by apericak** [comment]
Here are a bunch of screenshots of different ways of doing the erosion and dilation. The top of the screenshot contains the code changes per image. There's not much of an order here. 

1. ![1](https://cloud.githubusercontent.com/assets/15909902/16854016/2fe4e150-49dd-11e6-94d7-cb735e8e6329.JPG)

2. ![2](https://cloud.githubusercontent.com/assets/15909902/16854020/2fe783d8-49dd-11e6-9ff9-fa8c0dcd999f.JPG)

3. ![3](https://cloud.githubusercontent.com/assets/15909902/16854018/2fe640cc-49dd-11e6-92e8-e931640c28f0.JPG)

4. ![4](https://cloud.githubusercontent.com/assets/15909902/16854019/2fe65224-49dd-11e6-8b30-6cfed30fac3d.JPG)

5. ![5](https://cloud.githubusercontent.com/assets/15909902/16854015/2fe15eea-49dd-11e6-9416-6a892b7c8f70.JPG)

6. ![6](https://cloud.githubusercontent.com/assets/15909902/16854017/2fe52dea-49dd-11e6-8f28-d2ee9d30fc48.JPG)

7. ![7](https://cloud.githubusercontent.com/assets/15909902/16854062/623c041c-49dd-11e6-98a5-8411460b64d8.JPG)

8. ![8](https://cloud.githubusercontent.com/assets/15909902/16854021/2fea7e30-49dd-11e6-806a-2362510863d7.JPG)

9. ![9](https://cloud.githubusercontent.com/assets/15909902/16854022/2fef540a-49dd-11e6-9c38-beea3065d35e.JPG)

10. ![10](https://cloud.githubusercontent.com/assets/15909902/16854025/2ff1e792-49dd-11e6-8c78-7481207cfbfc.JPG)

11. ![11](https://cloud.githubusercontent.com/assets/15909902/16854024/2fefb95e-49dd-11e6-98a7-34c4c5b5e9d6.JPG)

12. ![12](https://cloud.githubusercontent.com/assets/15909902/16854023/2fef7ac0-49dd-11e6-8ab5-23f8062b7483.JPG)

Note that these aren't perfect because of how GEE shows results; i.e., if you were to zoom in, these might look different. However, to me image 11 (nearly identical to 3, which answers whether we need three or four steps) looks the closest to what I'm expecting. However, image 1 also looks good. In general, the images relying solely on 60 m distances seem worse, so I'd advocate moving back to a focus on 30 m. 

And in thinking about it some more, I don't really think it matters to have 60 m to match the early Landsats. If I'm interpreting it correctly, the Euclidean kernel we're using isn't selecting pixels, per se, it's just moving the given distance away from the pixel. So a 30 m kernel will select the four direct neighboring pixels exactly, but only those four. A 60 m kernel might select all eight neighbors, but it will only select the four neighbors on early Landsat. So, we might be okay (at least for the later Landsats) to use a 30 m kernel at times.

**Comment by cjthomas730** [comment]
@apericak this sounds good, and based the analysis script the 30 meter buffer is reimplemented. 
```java
  var mtrCleaned = mtr
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters'))  // erode
    .reduceNeighborhood(ee.Reducer.max(), ee.Kernel.euclidean(60, 'meters'))  // dilate
    .reduceNeighborhood(ee.Reducer.min(), ee.Kernel.euclidean(30, 'meters')); // erode
```

Unless there are any other issues, I think we can close this issue?
