### ISSUE TITLE
Restrict Time for Creation of our Greenest Pixel Composites

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#83]
We need to select a date range over which to create our Greenest pixel composites, ideally to exclude dates without greenest (winter and fall months).

**Comment by cjthomas730** [comment]
@apericak how does April --> September sound?

**Comment by apericak** [comment]
@cjthomas730 Ah yah sorry for not responding here--I actually don't think the issue is as simple as restricting what months we use. I'm exploring this now, and I'll discuss more this morning on the call, but I think the real reason for the cloud contamination in certain images is due to just having very few scenes in some areas. Depending on how good the data were, etc., USGS only has a few scenes (even for the non-MSS satellites) for some areas. I think it's in these areas where we tend to see cloud contamination, simply because there aren't enough images to make up for the fact that there are clouds in some images. So I don't know that restricting months of imagery will really help; it certainly won't hurt, because then we will just get more null values, but I suppose we want to think about whether that's something we want.
