### ISSUE TITLE
Follow Up with Nick Clinton

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#90]
After we're done with the pixel trajectory, @davidkroodsma will schedule his second meeting with Nick Clinton for feedback and to address his possible co-authorship

**Comment by apericak** [comment]
So @davidkroodsma and I met with Nick last week at the Geo for Good conference. Here's a summary of some of the ideas he had; David, please feel free to add anything you all discussed after I left:

**Improving thresholds:** One way we could consider setting the NDVI thresholds is via an ROC analysis, like I tried way earlier this summer. He cited [this paper](https://ccrma.stanford.edu/workshops/mir2009/references/ROCintro.pdf) that explains what ROC curves are and how they are calculated. In particular, he mentioned setting the thresholds so as to maximize the [F-measure](https://en.wikipedia.org/wiki/F1_score), which is equal to 2_pr_/(_p_+_r_), where _p_ is the precision (number of true positive results divided by number of all positive results) and _r_ is the recall (number of true positive results divided by number of actual positives that should have been returned). The possible issue I see with this approach, though, is that we don't have training data for every county in our study extent, so we would have to buffer out our training regions so that they covered all areas within the study extent and then set one threshold per buffered region. (Alternatively, we could generate more training data, but at this point the gains probably wouldn't justify that time cost.) Nonetheless, it might be interesting to use ROC analysis to evaluate the county-level thresholds in counties where we do have training data, to see how good our NDVI thresholding method is working.

**Small areas:** He really didn't have a great solution for how to selectively choose small mine areas and separate those from noise pixels, other than setting some size threshold and limiting mines to that threshold (in other words, this would ignore some small mines, so that our overall accuracy would improve.) He was brainstorming about perhaps finding some other spectral fingerprint of mined areas so as to differentiate between non-mine areas; this could be as simple as setting a threshold for a specific band (e.g., and I'm just making this up, but a mine requires a red-band value greater than 0.3), but more likely would require some other index or band math. As we've discussed before, this might be a good future improvement, but may not be worth the time now.

**Specific timing / pixel trajectory / reclamation analysis:** Remember that this won't be discussed in this first paper, and is a follow-up project to what we are currently making. Nonetheless, Nick suggested that once we have yearly mining polygons (current paper), we find the [cumulative anomalies](https://developers.google.com/earth-engine/ic_iterating) (EE documentation example) in each polygon, using everything before the known date of mining as the baseline. In other words, since we know (approximately) when mining began, we would first find the average NDVI per polygon (or per pixel within the polygon) of every image prior to the year where we first identified mining in that polygon. This average NDVI should be pretty high since it should consistently be forested land. This average is then our baseline for that polygon. We then would look at the next image's NDVI in that polygon (once mining has started), and subtract the baseline mean from the image's NDVI. If the baseline was 0.7 and the next image was 0.3, the result would be -0.4. If the subsequent image had an NDVI of 0.25, the subtraction (using the original 0.7 baseline) would result in -0.45. In short, we would do this subtraction for each image after the baseline date. Then, we add the results together in iteration (1st image + 2nd image = n1, n1 + 3rd image = n2, n2 + 4th image = n3, etc.) Given what we know about mining, these iterative sums would decrease over time (i.e., any decrease represents a lower-than-average NDVI for that image), but as the landscape begins to recover the sum would gradually start leveling off (the difference between average and the image would be negative but closer to zero), or even increasing if an image had an NDVI greater than 0.7 (the difference would be greater than 0.) By plotting the shape of this cumulative anomaly curve, we could see the dates at which this stabilization and recovery began.
